name: repo_scout_app
description: "Github repository explorer"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0 
  get_it: ^8.2.0
  injectable: ^2.5.1
  go_router: ^8.1.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  injectable_generator: ^2.8.1
  flutter_lints: ^5.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true